name: dio_handler
description: Handle network API requests with Dio.
version: 0.0.1-beta-1
homepage: https://arfaz.tech
repository: https://github.com/Arfaz123/dio_handler.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: any
  dio: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

#  assets:
#    - assets/images/
#    - assets/icons/
